name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/CI-CD/.github/workflows/build-dotnet.yml@main
    secrets: inherit
    with:
      project_path: 'Infrastructure.csproj'
      test_path: 'Infrastructure.Tests/Infrastructure.Tests.csproj'
      dependencies: 'Platform-System/Application,Platform-System/BuildingBlocks,Platform-System/Domain'



